version: '3.7'
services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=example
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - $PWD/pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - 5434:5432
    networks:
      - kong
    restart: on-failure

  migrations:
    image: kong
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=192.168.31.124
      - KONG_PG_PORT=5434
      - KONG_PG_USER=postgres
      - KONG_PG_PASSWORD=example
      - KONG_CASSANDRA_CONTACT_POINTS=kong
    networks:
      - kong
    depends_on:
      - postgres
    command: kong migrations bootstrap

  kong:
    image: kong
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=192.168.31.124
      - KONG_PG_PORT=5434
      - KONG_PG_USER=postgres
      - KONG_PG_PASSWORD=example
      - KONG_CASSANDRA_CONTACT_POINTS=kong
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
    depends_on:
      - postgres
      - migrations
    networks:
      - kong

  konga:
    image: pantsel/konga
    environment:
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_CASSANDRA_CONTACT_POINTS=db
      - KONG_PG_HOST=192.168.31.124
      - KONG_PG_PORT=5434
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_PG_DATABASE=kong
      - KONG_DATABASE=postgres
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
    ports:
      - 1337:1337
    depends_on:
      - postgres
      - kong
    networks:
      - kong
  
volumes:
  pgdata: {}

networks:
  kong: {}